### ISSUE TITLE
リポジトリがカオスな件

### ISSUE THREAD

**Issue by Bakudankun** [monacoinproject/monacoin#10]
### 問題点

現在このリポジトリには以下のような問題が放置されています。
- 「0.8.7.1」といったバージョン番号を名前としたブランチが存在する
- しかもブランチ0.8.7.0がタグ0.8.7.0と違うコミットを指している
- ブランチ「8.6.1」の存在（0.8.6.1では？）
- ブランチにあってタグに無いバージョン番号（0.8.6台）
- ブランチmasterが遥か後方のバージョン0.8.6.2を指している
- それに対する対応が何故か「リポジトリのHEAD（デフォルトブランチ）をブランチ0.8.7.1にする」というもの
- 0.8.7.1の次が0.10.2.2という謎の命名規則
- しかもその0.10.2.2にどんどんコミットが作られてnextブランチと全く違った内容になっており、開発者のコメントが読めるブログなども無いためどちらが次期バージョンなのかわからない
- さらにこのissueを書いている間にブランチ0.10.2.2-Lyra2REv2が作られもはやカオス

これでは他の開発者のみならず利用者も混乱し、Monacoinの成長を大いに阻害する要因になっていると思います。
### 解決案
- バージョン番号を名前としたブランチ（ただし0.10.2.2以外）をタグに移行して削除する
- その際にブランチ8.6.1をタグ0.8.6.1に修正する
- ブランチmasterを現行バージョンの0.8.7.1に同期させ、リポジトリのデフォルトブランチをmasterに戻す
- nextと0.10.2.2のどちらが次期バージョン開発ブランチなのかはっきりさせ、それをnextブランチとする（nextが次期バージョンでないなら削除する）

開発者が全くコメントを発信せず「謎の人物」になってしまっていることもMonacoin発展の阻害要因だと思うので、できれば開発者の意向が読めるブログなども作ってくださると嬉しいのですが、少なくともこれらの点は修正していただきたいです。
### バージョン番号の命名規則について

なお、バージョン番号の命名規則には広く使われている[Semantic Versioning](http://semver.org/lang/ja/)をおすすめします。

これはバージョン番号はa.b.cのように３段階にし、マイニングアルゴリズム変更など互換性のない変更ではaの数を、機能拡張など互換性を保った変更はbの数を、バグフィクスなどの軽微な変更ではcの数を上げるというものです。

広く使われている命名規則の方が新しい開発協力者が集まりやすいと思います。バージョン１からはそのようにしてみてはいかがでしょうか？

**Comment by monacoinproject** [comment]
・バージョン番号の命名規則について
　ほぼ全てのAltcoinがbitcoinに倣っています。
　MonacoinのベースとなるLitecoinもまた、0.8から0.10へ飛んでリリースされています。
　これらはbitcoin coreの実装内容と対応するため、独自のバージョン規則は避けた方が良いと考えます。

・リポジトリのHEADがブランチ0.8.7.1
　gitから直接ソースを取得するサービス開発者にデフォルトで0.8.7.1を取得させるためです。

・nextブランチ
　これについては現状未定のため保留しております。
　同じく0.10.2.2、0.10.2.2-Lyra2REv2もリリースされるかは未定です。

・さらにこのissueを書いている間にブランチ0.10.2.2-Lyra2REv2が作られもはやカオス
　ブランチは開発の都合で作られるものと理解しております。

・開発者が全くコメントを発信せず「謎の人物」になってしまっていることもMonacoin発展の阻害要因だと思う
　暗号通貨自体、「どうしていくかは利用者に委ねられているもの」で、誰が開発したかは大した問題ではないのです。
　開発者主導でなければ発展できないAltcoinは自然に消えるでしょう。

・ブランチ「8.6.1」の存在（0.8.6.1では？）
・ブランチmasterが遥か後方のバージョン0.8.6.2を指している
　うん、いい加減だねMonacoinproject。

**Comment by Bakudankun** [comment]
お返事・対応ありがとうございます！

Litecoinのバージョンが飛んでいることは知りませんでした。
そう言われれば確かに、ネットワークでバージョン番号の確認とかし合っているだろうし命名規則を変えてしまうのは危なそうですね。早計でした！

ということは、ブランチやバージョンの番号はだいたいベースとなっているLitecoinのバージョン番号ということなのですね？
それならば0.10.2.2-Lyra2REv2ブランチの意味も理解できます。Litecoinの件を知らず、「突然飛んだリリース番号（ただし未公開）にさらにトピック名がついたブランチが作られている？？？」と混乱してしまっていました。

> 暗号通貨自体、「どうしていくかは利用者に委ねられているもの」で、誰が開発したかは大した問題ではないのです。

確かにそれはそうなのですが、一応貴殿が総本山であり、「Monacoin」について事実上最終決定権を握っていると言えると思います。
今回のアルゴリズム変更の件も各所では憶測で議論している状態ですし、Twitterや2chでもいいので緩く情報発信していただければ皆の不安も和らぐと思うのです。

**Comment by monacoinproject** [comment]
・ということは、ブランチやバージョンの番号はだいたいベースとなっているLitecoinのバージョン番号ということなのですね？

はい。
（基本的には）最下位を除いたバージョン番号(ex. 0.10.2)は、同バージョンのLitecoinの追加・修正が反映されていることを意味します。

**Comment by Bakudankun** [comment]
把握です！
