### ISSUE TITLE
有効なコマンドでHelpに記述されていないものが数個あります

### ISSUE THREAD

**Issue by mal1nuxer** [monacoinproject/monacoin#11]
walletlock, walletpassphrase, walletpassphrasechange
reconsiderblock
setmocktime

これらのhelpへの記述がありませんでした

**Comment by monacoinproject** [comment]
reconsiderblock, setmocktime は元々ヘルプ非表示の項目です。
walletlock, walletpassphrase, walletpassphrasechange は検討します。

**Comment by mal1nuxer** [comment]
なるほど。help [command]とすると一応それぞれ出てくるようですが
monacoinの他は扱ったことがなかったので暗号通貨ソフトウェア全体的にはそういう仕様になっているのでしょうね。
wallet*に関しては0.8の頃は使えてたのでちょっと違和感がありました。(こちらでやったイベントでそのコマンド使うのも指南していたので特に。。。)

issueに書いちゃダメだと思うけど、またヤル気出して最近のブロックチェーン技術のここが熱い解説してね(´・ω・｀)
