### ISSUE TITLE
Updated new wallet but always reports: Monacoin is downloading blocks...

### ISSUE THREAD

**Issue by crackfoo** [monacoinproject/monacoin#13]
it seems something is not right with the new wallet.... it always reports downloading blocks even when it is up-to-date....

monacoin-cli getblocktemplate
error code: -10
error message:
Monacoin is downloading blocks...

**Comment by monacoinproject** [comment]
I fixed the bug you pointed out. 
thank you.

**Comment by crackfoo** [comment]
Thanks, that fixed the issue.
