### ISSUE TITLE
RPC連続アクセスが制限されます

### ISSUE THREAD

**Issue by namuyan** [monacoinproject/monacoin#15]
localhostよりRPCに高頻度でアクセスしています。
しかし他のcoindと比べると500エラーによりアクセスを制限されます。
おそらくDDOS対策が組み込まれていると思われますが、コマンドや起動オプションで解除できませんでしょうか？

**Comment by monacoinproject** [comment]
monacoindは500エラーと共にエラーメッセージを返しているので、それを参照して原因を調査してください。
PHPで"jsonRPCClient"を使用している場合は、"jsonRPCClient"が500エラーに対して"Unable to connect"として返すため、monacoindからのエラーメッセージは取得できません。
EasyBitcoin-PHP等を使用してください。

**Comment by namuyan** [comment]
PerlのJSON::RPC::Client を用いています。
いろいろ調べたところ、
Perl　JSON::RPC::Client　→　450回前後で500エラー(以降Perlプログラムを閉じるまで500エラー継続)
PHP　jsonRPCClient →　450回前後で500エラー(以降PHPプログラムを閉じるまで500エラー継続)
PHP　EasyBitcoin-PHP →　3万回近いアクセスの後に応答不能(エラーメッセージはありませんでした、1分以内に復帰)

CoindではなくJSONRPCモジュールに問題があるかもしれません。CURLの使用を検討します。
