### ISSUE TITLE
v0.13.2.2-a8aa999 doesn't start

### ISSUE THREAD

**Issue by mrfish12** [monacoinproject/monacoin#16]
Dear Monacoin Team,
A few days ago, I downloaded the new Monacoin version from your website. Unfortunately, this version does not start, please see the screnshot:
![mona_error](https://user-images.githubusercontent.com/29313506/26992348-8a45a30c-4d5e-11e7-9a90-2238bc260e25.png)
Maybe there are more people with the same start error message?
Could you help me please? Currently, I have no access to my coins.
Thanks a lot :)
Kai

**Comment by monacoinproject** [comment]
I see that the error is a database error. To fix the error, a reindex is required. On windows, right click the shortcut and select properties. Then in the box labeled Target, go to the end of the line, hit space, and add

 `-reindex`

That will reindex the database which can take a few hours, but not as long as redownloading. That should fix the problem. None of your coins will be lost.

**Comment by mrfish12** [comment]
Thank you very much for the quick response! Kai

 Am 12-Jun-2017 06:57:18 +0200 schrieb notifications@github.com: 

I see that the error is a database error. To fix the error, a reindex is required. On windows, right click the shortcut and select properties. Then in the box labeled Target, go to the end of the line, hit space, and add 

-reindex 

That will reindex the database which can take a few hours, but not as long as redownloading. That should fix the problem. None of your coins will be lost. 

--
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.    

-------------------------------------------------------------------------------------------------
FreeMail powered by mail.de - MEHR SICHERHEIT, SERIOSITÄT UND KOMFORT
