### ISSUE TITLE
次期アップデートで反映されるであろうBIP-173のhuman-readable partは決まっていますか？

### ISSUE THREAD

**Issue by wakiyamap** [monacoinproject/monacoin#19]
litecoinにおいて次期アップデートでBIP-173が適応されるようです。
BIP-173について
https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki

この中でhuman-readable partと言うものがあるのですがこれが各通貨のシンボルとなり
BTCではmainnet[bc1],testnet[tb1]
LTCではmainnet[ltc1],testnet[tltc1]　参考： https://github.com/litecoin-project/litecoin/issues/312
がそれぞれsegwit使用時のアドレスの頭文字として使われる予定のようです。

Monacoinにおいてはどのようなシンボルにする予定でしょうか？

**Comment by monacoinproject** [comment]
litecoin core 0.15.0のブランチではBIP173サポートはまだ無いようですが、LNの方が先行しているのですね。
同じく通貨コード＋セパレーター mona1, tmona1 でどうでしょうか。

**Comment by wakiyamap** [comment]
文字の制限はありますが、
文字数制限が本家で言及されてないので実装がどうなるか次第かな…と考えましたが問題なさそうですね。

ありがとうございます！
