### ISSUE TITLE
Problem implementing mining-pool support for Monacoin

### ISSUE THREAD

**Issue by oliverw** [monacoinproject/monacoin#21]
I'm currently working to implement support for Monacoin into our stratum mining engine: https://github.com/coinfoundry/miningcore

Supporting new coins based on bitcoin-core is normally straight forward but somehow I must be missing something. Below is a link to the part where the hashing is configured for all supported coins:

https://github.com/coinfoundry/miningcore/blob/master/src/MiningCore/Blockchain/Bitcoin/BitcoinJobManager.cs#L248

Do you see anything that's incorrect?

**Comment by imrecsoka** [comment]
Hi, how do you actually mine this coin SOLO with the conf file, is this possible?
I can not connect, and i hope there is support for this coin on here ?
I was just looking for other life on here , so i saw Oliver giving his news about integrating this coin in to his pool, cheers for that.
Maybe you can also help or suggest about my issue ?
I can post a full synopsis of my trying to mine.

**Comment by oliverw** [comment]
Solved

**Comment by imrecsoka** [comment]
Hi Oliver,

Thanks for letting me know.
