### ISSUE TITLE
Can you SOLO mine Monacoin ?

### ISSUE THREAD

**Issue by imrecsoka** [monacoinproject/monacoin#22]
Can you SOLO mine Monacoin ?

Thank you.

**Comment by wakiyamap** [comment]
It can be possible.
Please write your environment.

or

You can ask questions on the bulletin board.
https://askmona.org/

good luck !!

**Comment by imrecsoka** [comment]
Hi, the page is in another language so i cant really use it? i tried to translate it and create a log in account but i cant.

**Comment by tsgirl** [comment]
Technically yes, economically probably not.
