### ISSUE TITLE
How do you mine Monacoin?

### ISSUE THREAD

**Issue by uchihadesendent** [monacoinproject/monacoin#23]
I downloaded the Monacoin wallet and got it synched and caught up but after that, I have no clue what I'm supposed to do, I know it needs files and codes to work but that's about it. I would greatly appreciate any help with what I need to do.

**Comment by imrecsoka** [comment]
Download sgminer, from github
Then find a monacoin pool to mine from. It might be anonymous or you will have to register an account like uchihad.worker1
Then run sgminer -k Lyra2REv2/lyra2v2 -o {pool hostname:port} -u uchihad.worker1 -p password
Hope this works, if not let me know.
