### ISSUE TITLE
P2Pool for Monacoin

### ISSUE THREAD

**Issue by Tanariel** [monacoinproject/monacoin#25]
Sorry, i didn't find a way to contact the dev team otherwise than by creating an issue.

Would there be a way to provide a p2pool repository with the adapted version of the code for the monacoin like it exists for vertcoin ?  (https://github.com/vertcoin/p2pool-vtc) ?

Is there a lot of changes to do for t to run with monacoin ?

Thanks in advance for you great work and your support.

**Comment by monacoinproject** [comment]
Sorry, I don’t know much about p2pool.
