### ISSUE TITLE
Monacoin Core - wallet/crypter.cpp, line 198 Wrong Passphrase Passaword

### ISSUE THREAD

**Issue by c4kbeast** [monacoinproject/monacoin#26]
OS Windows 10 64bit
Monacoin core 
v0.14.2.0-6d65019 (64-bit)

Hi
I have some problem with my wallet
passphrase is 100% correct
I can see the balance, but when I enter the right passphrase to send the currency or change passphrase.
This message appears

Assertion failed!
file: wallet/crypter.cpp, line 198

- the program opens and synchronizer without problems
- I tested the backup on another computer and it presented same problem.

**Comment by monacoinproject** [comment]
The wallet is probably corrupted.
It's may be impossible to salvage wallet.dat.

**Comment by cryptcoin-junkey** [comment]
May duplicate #24
