### ISSUE TITLE
Mailing list

### ISSUE THREAD

**Issue by RayKitajima** [monacoinproject/monacoin#3]
Could you open a project page for monacoin in Sourceforge? (or some other place having mailing list supports, but sf may be the best)

We may need mailing lists to discuss and maintain monacoin and its community from technology aspect.

thanks!

**Comment by gikopool** [comment]
I deeply agree with your suggestion to have a mailing list for monacoin developers!

それと、githubのissue含めて、議論の主要言語は日本語で良いと思います。
その方が開発者の参入障壁が下がるでしょう。
もちろん、英語話者の方が興味を持たれたら、その際は英語で対応するということで。
＃ ↑別にissueを建てるべき話題だったかも。。。

**Comment by visvirial** [comment]
わたなべ氏からの応答も暫くないようですし、必要だと思うのであれば勝手に作ってしまっていいんじゃないんですか？

**Comment by ohac** [comment]
メーリングリストを作るのであれば参加したいです。
ところでkeystore00さんのリポジトリ、最新のLitecoinとマージしたみたいですね。
といった話題も書けるのでよさそうです。

**Comment by gikopool** [comment]
sourceforge.jp上に当リポジトリのミラーを作りました。
https://sourceforge.jp/projects/monacoin
1日に一度程度、cron等を用いて自動的にgithubから変更をpullし、
sourceforgeへpushすることで恒常的なミラーにする計画です。

sourceforge側で変更を感知すると、次のMLに通知するように設定しました。
http://lists.sourceforge.jp/mailman/listinfo/monacoin-dev
monacoin開発状況の把握のほか、開発者同士のコミュニケーションにも
ご活用ください。

**Comment by RayKitajima** [comment]
gikopoolさん、ありがとうございます。
ML出来ましたのでCloseさせていただきます。
