### ISSUE TITLE
Build Wallet From QT 4.8

### ISSUE THREAD

**Issue by BlackcatIvan** [monacoinproject/monacoin#30]
Hello to everyone! 
So i want to make a different version of this wallet but when i try to build with QT 4.8.7 i get the follow error

Using the QT 4.8.7  MSVC2008 32 bit
10:34:48: Configuration is faulty. Check the Issues view for details.
Error while building/deploying project bitcoin-qt (kit: Desktop Qt 4.8.7 MSVC2008 32bit)
When executing step "Make"

Windows 10 64bit 
AMD FX9590 5.3Ghz
16 GB ram 
GTX1080 
M.2 512GB 

![52345](https://user-images.githubusercontent.com/35800837/35384047-0275bf58-01bc-11e8-9912-d9fc5c5f6cd5.PNG)
![6234634](https://user-images.githubusercontent.com/35800837/35384049-02985a18-01bc-11e8-9e9f-088f817d0878.PNG)

**Comment by cryptcoin-junkey** [comment]
I think this is not caused by Monacoin-core itself. But your build environment. Google "No winrtrunner.exe found."
