### ISSUE TITLE
Bittrex closed its wallet - it says "Wallet Offline - Dev requested"

### ISSUE THREAD

**Issue by a1binos** [monacoinproject/monacoin#37]
Hi.
Bittrex closed mona wallet. "Wallet Offline - Dev requested " 

Did development team knows about it?
Any ETA on solution?

**Comment by TOTANICS** [comment]
Can someone from Dev comment on this please? Not good for me having my bittrex MONA wallet offline for this long!

**Comment by wakiyamap** [comment]
My friend sent a security report to bittrex on 17th May,
It seems that it became "Wallet Offline - Dev requested".

Watanabe (monacoin dev) thinks that mail comes from bittrex.
Perhaps bittrex dev wants to know more?

Since the measure is according to this issue, I think that it is waiting for communication from watanabe to bittrex dev.
https://github.com/monacoinproject/monacoin/issues/36

**Comment by lae** [comment]
Dev has communicated with Bittrex over Slack, explaining that a permanent countermeasure is still being deliberated on, but exchanges for the time being can increase required confirmations to prevent malicious effects from selfish mining.

It's really just up to Bittrex to follow suit of other exchanges following this advice (which was provided on 18 May, but they have not).

**Comment by donaldyang** [comment]
Dev plz communicated with LiveCoin too.Livecoin is waiting the response from dev now.

**Comment by Rekamserg** [comment]
Bittrex support said that the wallet was closed at the request of the developer.

**Comment by djhoangwar** [comment]
Why wallet still not active on bittrex ? so worry

**Comment by ken054321** [comment]
when will they open it again? what is monacoin plan?

**Comment by paulpoco** [comment]
Yes when?

**Comment by lae** [comment]
"dev requested" on the Bittrex status page means that Bittrex was requesting a developer.

The wallet *was not closed at the request of the developer*. The developer advised increasing confirmations to 100, however Bittrex appears to not want to heed that advice and wants damages to be compensated, which is outside the ability of the development team.

**Comment by ohac** [comment]
Please read  the COPYING file.

https://github.com/monacoinproject/monacoin/blob/master-0.15/COPYING#L18

> THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.

**Comment by lae** [comment]
That makes for a heavy precedent, you realise that, right?

**Comment by Rekamserg** [comment]
Will the coin from the fact that they remove wallets from Bittrex and Livecoin?
What does the developer think about the coin owners, who got the coins stuck on the Bittrex and Livecoin?

**Comment by paulpoco** [comment]
Fix the wallet already!

**Comment by tiltsince87** [comment]
Devs, please send an answer to both Livecoin and Bittrex in order to get deposits/withdraws going. This could possibly become a $100m drop if it's not fixed/communicated soon.

**Comment by Rekamserg** [comment]
why not 200?

**Comment by Rekamserg** [comment]
This is good news. Remained Livecoin ...
