### ISSUE TITLE
モナコインのベクター形式／高解像度の汎用ロゴ

### ISSUE THREAD

**Issue by Gem-Gem** [monacoinproject/monacoin#40]
monacoinproject ワタナベ さま

こんにちは
このたび
・公式ロゴがラスター形式で、サイズが500pxほどと小さい
・2値にしにくい
ということで、グッズ制作や広告などにも対応できるロゴを公式からダウンロードができれば…というお話をいただきましたため、汎用タイプのロゴを作成致しました。

リクエストしようと思ったのですが、画像の格納場所やご連絡先がわからず…こちらでご案内お願いしたいと思います。

![monamark2](https://user-images.githubusercontent.com/39252606/40740434-d0e6f738-6483-11e8-9c1c-8d1e8518da11.jpg)

・2048px/png モノクロ モナー
・2048px/png モノクロ  M
・2048px/png ブラウン（ゴールド） モナー
・2048px/png ブラウン（ゴールド） M
・ai ベクターデータ　（6パターン入）
全部で5ファイル or zipなのですが、
こうしたファイルはどうやってリクエストしたらよいでしょうか？

お手数おかけしますが、
ご案内どうぞよろしくお願いいたします

**Comment by monacoinproject** [comment]
今後もいろいろなデザインが出てくると思うので、どこかで一覧が見れてダウンロードできる場所があるといいですね。
monacoin.orgからそこにリンクを張るという形で。

monacoinprojectをOrganizationに切り替えて誰かにページを作ってもらうのもアリか…

**Comment by Gem-Gem** [comment]
お世話になっております。
色々外部サービスやサイト作成を検討しました結果、もし可能であれば、

「monacoinprojectをOrganizationに切り替えて誰かにページを作ってもらう」

という方法がやはり一番誰もがわかりやすく、理想なのではないかと思いました。
Organizationというのは、ウェブページの管理の権限を、制作者にも広げてくださるということで間違いないでしょうか？
その場合、ウェブ制作ができて、GitHubにも詳しい方を募集し、こちらでまたお声をおかけすればよいでしょうか？

お手数おかけしますが、お時間ございますときにご案内よろしくお願いいたします。

**Comment by Gem-Gem** [comment]
cryptcoin-junkeyさま、ご連絡ありがとうございます。権利の件承知いたしました。大変お手数をおかけしますが、引き続きどうぞよろしくお願いいたします。

**Comment by cryptozeny** [comment]
デザインの最高

**Comment by wakiyamap** [comment]
@cryptcoin-junkey 
このアイコンを別件で使用したいのですが、法務上、事前にクリアにしておかねばいけない事柄とは何でしょうか？
