### ISSUE TITLE
Huge amount of stuck MONA coins on Livecoin

### ISSUE THREAD

**Issue by tiltsince87** [monacoinproject/monacoin#42]
There's a big amount of MONA coins stuck on Livecoin due to the attack, take your responsibility and fix this.

Message from Livecoin:
"Dear clients, as you all know, MONA network has been attacked recently, and all the exchanges suffered at some point due to fake incoming transactions. The fact of attack has been publicly acknowledged by the developers.

We contacted the developers several times on the issues concerning the cancellation of fake transactions or providing compensations for the losses sustained by the exchanges as a result of the hackers' attack on MONA blockchain. Today we got an answer: the developers won't take any actions. We, in our turn, have nothing to do than keep MONA deposit/withdrawal closed, in accordance with the terms of services providing. If the developers of MONA will ever take steps to cover the losses, incurred by the attack on the blockchain, we would be glad to make this asset available again. If you want to influence the situation somehow, please, send collective claims to MONA developers."

Source: https://www.livecoin.net/news/view/719?lang=en

**Comment by lae** [comment]
This is not the responsibility of the developer to "fix" retroactively.

A feature was pushed to the Monacoin client to help exchanges and merchants prevent theirselves from being affected by this type of attack in the future (which, mind you, is possible on pretty much every Bitcoin clone). It's the responsibility of exchanges to make use of this type of security.

The only solutions (rollback, premine) that have come up to "cover losses" all are completely controversial and require that the community accepts the solution. The developer can't fix the will of thousands of people.

If you have any ideas for a possible solution that benefits the entire community at large, then please say so. This type of issue does nothing to help anyone.

**Comment by KaiShoya** [comment]
@tiltsince87 MONA coin project's License is MIT License. Livecoin knew about it and should have used it.
https://github.com/monacoinproject/monacoin/blob/master-0.15/COPYING

**Comment by Rekamserg** [comment]
It's good that the coins are simply stuck on the stock exchange. For many, they are stuck in transactions. And they can not be sold already. Why Livecio all dumps on the developers - it's not clear. Some of their guilt is also there. Apparently the question will be eternal and the means are lost.
