### ISSUE TITLE
pchMessageStartがlitecoinと一緒の件について

### ISSUE THREAD

**Issue by wakiyamap** [monacoinproject/monacoin#44]
今のところ特に問題はないかと思いますが、そのうち指摘が来そうなので一応issue投げておきます。
ただ、gamecredit辺りも同じ値になっているのであまり急ぐ必要はないとは考えます。

litecoin https://github.com/litecoin-project/litecoin/blob/master/src/chainparams.cpp#L115-#L118
monacoin https://github.com/monacoinproject/monacoin/blob/master-0.15/src/chainparams.cpp#L120-#L123

参考のpchMessageStart変更に関わるfeathercoinでの実装例
https://github.com/FeatherCoin/Feathercoin/commit/19f116dec8a1bf1156d03f85aad36e4900318821

**Comment by monacoinproject** [comment]
ご指摘ありがとうございます。
確かに変更したほうがCMessageHeader::IsValid()の時点で弾くことができるので望ましいです。
ただポートも異なりますし、仮にlitecoindと接続してもBANされるので今のところは問題ないかと思います。

（４年前の記憶ではfeathercoinはGenesisBlockなどもlitecoinと同じだった？ような気がするので、変更しないと問題あるかもしれません）

**Comment by wakiyamap** [comment]
DNS seedの時点で弾けてるよなぁと思いつつ、
実質的に被害にあった経験があまり感じられないのでまぁ問題ないよなとは考えておりました。

確かにdefault portが違うので故意にやらない限りは接続自体しなさそうですね。
回答ありがとうございました。

**Comment by monacoinproject** [comment]
pchMessageStartはメッセージであることのマジックナンバーでしかなく、validationとは無関係なので、仮に他のコインと同じ値でそのコインのクライアントと接続されたとしても、何かしら被害に遭うという事は無いです。
（以前のfeathercoinはポートが違うだけの中身litecoinそのままだったと思うので、そういった場合は問題があると思います）
