### ISSUE TITLE
libbitcoinconsensusのこと

### ISSUE THREAD

**Issue by lae** [monacoinproject/monacoin#48]
前からArchのパッケージを維持していて、一つのことを気づきました。他のフォークはlibbitcoinconsensusをリネームしてるけどmonacoinはそうしない。必要ないでしょうか？

たとえば、0.15.1向けこのチェンジを行いました
https://aur.archlinux.org/cgit/aur.git/tree/0001-rename-libbitcoinconsensus-to-libmonacoinconsensus.patch?h=monacoin-qt&id=78c5666016dfeaa451f8a4652012084306832335

第三者のアプリ開発に必要ないならあんまり気にせず0.16.3に更新しますが、あったほうがいいなら本家に投入したいと思う

**Comment by monacoinproject** [comment]
laeさん、いつも有難うございます。
是非master-0.16ブランチにpull requestください。

**Comment by lae** [comment]
dogecoinのソースを確認したら、そのリネームのチェンジが0.11になくなったらしいので一旦遠慮しときます。必要条件見つかったらPR送ります。
