### ISSUE TITLE
monacoind(0.16.3) update for bittrex

### ISSUE THREAD

**Issue by wakiyamap** [monacoinproject/monacoin#49]
I asked bittrex to update monacoind and the following sentences came back.
`"If you are not one of the Coin's developers or representative from the coin team we will not be responding to your ticket. Please do not submit this form if you answer NO."`

Tentatively, can you approve here by saying `representative from the coin team`?

Bittrexにmonacoindのアップデートをお願いしたところ以下のような文章が返ってきました。
`コインの開発者やコインチームの代理人でなければ、あなたのチケットには返答しません。あなたが「いいえ」と答えた場合は、このフォームを提出しないでください。`

仮に、ここで代理人として承認をしていただけることは可能でしょうか？

**Comment by lae** [comment]
私はbittrexのslackにいるので、一応対応してます

**Comment by wakiyamap** [comment]
@lae ありがとう！

**Comment by lae** [comment]
![image](https://user-images.githubusercontent.com/1318013/46214228-a0226a00-c375-11e8-834a-87d916693d20.png)
完了らしい
