### ISSUE TITLE
Chainfiles please?

### ISSUE THREAD

**Issue by Jan041001** [monacoinproject/monacoin#50]
Hi Guys,

downloaded the Monacoin Core wallet and now i have to download the last 4 years and 38 hours..... This takes years to download..

My question.. You have chainfiles or a way to speed up the download that i can use this wall? 

If yes, please send me a link..

Best regards, 
Jan

**Comment by cryptcoin-junkey** [comment]
No. AFAIK, nobody provides chainfiles.
