### ISSUE TITLE
Digisheld or Digishield?

### ISSUE THREAD

**Issue by cryptozeny** [monacoinproject/monacoin#52]
https://github.com/monacoinproject/monacoin/blob/af84510ba17f461518d1b04c8fb10abc44e19c3f/src/chainparams.cpp#L87

Digi`sheld` or Digi`shield`?

it's not an actual problem, but i wonder to know... :thinking:

**Comment by monacoinproject** [comment]
"i" is missing
sorry for the typo.

**Comment by cryptozeny** [comment]
I want to contribute. Can I make a PR?

**Comment by cryptozeny** [comment]
merged

https://github.com/monacoinproject/monacoin/pull/53#issuecomment-439642752
