### ISSUE TITLE
wiki の無効化

### ISSUE THREAD

**Issue by wakiyamap** [monacoinproject/monacoin#56]
wikiが誰でも編集できると報告に来てくれたようです。
https://github.com/monacoinproject/monacoin/wiki/Publicly-Editable-wiki-bug

wiki の無効化方法です。
https://help.github.com/articles/disabling-wikis/

**Comment by lae** [comment]
A wiki is typically *supposed* to be open to public contributions. That's what a wiki is. That guy is just being an ass.

**Comment by cryptcoin-junkey** [comment]
Thanks for your report. I disabled the wiki. (as currently not used.)
I close it. Please reopen if there have another issues related on this issue.
