### ISSUE TITLE
How to contact the developers?

### ISSUE THREAD

**Issue by jkrebs** [monacoinproject/monacoin#57]
Hi there,

I am interested in the Monacoin project and would like to get in touch with the founders or developers to discuss a possible partnership.

Do you have a contact e-mail address?

Thanks!

**Comment by lae** [comment]
<organizationname>@gmail.com

But I would assume you might not get an answer especially if you don't contact using Japanese.

**Comment by cryptcoin-junkey** [comment]
Close as the question was answered. Thanks @lae
