### ISSUE TITLE
@wakiyamap @darekasann Can I close this issue?

### ISSUE THREAD

**Issue by nicetyshop** [monacoinproject/monacoin#67]
@wakiyamap @darekasann Can I close this issue?

@nicetyshop Thank you for your report. Your daily watches will contribute the node network of Monacoin safer. Please feel free to raise a issue here if you got any concerns about a vulnerability.

_Originally posted by @cryptcoin-junkey in https://github.com/monacoinproject/monacoin/issues/64#issuecomment-570774670_

I have been missing for many days. I try to collect various information. Please see the pictures I sent. You will see the irrationality of the number of asic and unusual hashrate. Can you tell me what caused it? As I looked at the attacks or the abnormalities, the thieves could directly strike at the AlraM Lyra2REv2 because it can be observed that every coin that uses Lyra2REv2 has an abnormally high def or hashrate. And I have already checked the asic manufacturer and got the answer that there is no new version of asic at this time

私は何日も行っていますが、いろいろな情報を集めようとしています。 asicと異常なハッシュレートの数の非合理性がわかります。何が原因か教えてください。攻撃または異常を見たとき、Lyra2REv2を使用するすべてのコインが異常に高いdefまたはhashrateを持っていることが観察できるため、泥棒はAlraM Lyra2REv2を直接攻撃する可能性があります。そして、私はasicプロデューサーをチェックしましたが、現時点ではasicの新しいバージョンはないという答えがあります

https://uppic.cc/v/6yXa
https://uppic.cc/v/6yXb
https://uppic.cc/v/6yXv
https://uppic.cc/v/6yXP
https://uppic.cc/v/6yXQ
https://uppic.cc/v/6yXR
https://uppic.cc/v/6yXS

**Comment by wakiyamap** [comment]
dupulicated https://github.com/monacoinproject/monacoin/issues/64
