### ISSUE TITLE
Revert "volatile-checkpoint" and "alert".

### ISSUE THREAD

**Issue by cryptcoin-junkey** [monacoinproject/monacoin#78]
I suppose recent hashrates of Monacoin mainnet is enough powerful to avoid selfish mining attack.
It's a time to revert "volatile-checkpoint" and "alert" functions, IMO.

**Comment by wakiyamap** [comment]
I think it's better to wait until 22.0 release.
However, if you want to change it, monad is going to change it soon too.

**Comment by cryptcoin-junkey** [comment]
I think there is no need to revert on 0.17.x.
on 0.18 preview also.

My suggestion is 0.19 or later.

**Comment by cryptcoin-junkey** [comment]
Done in 0.20.2.
