### ISSUE TITLE
No DNS Seeds on Testnet

### ISSUE THREAD

**Issue by Belial-public** [monacoinproject/monacoin#87]
There is currently no online nodes when you start the client on testnet. It's also quite hard to find an IP list online that has nodes that are alive.

Is it possible to update this with a couple of long active nodes in the near future?

**Comment by wakiyamap** [comment]
![image](https://user-images.githubusercontent.com/7189933/112933896-a585e880-915b-11eb-8089-06b8637c0012.png)
It seems that `testnet-dnsseed.monacoin.org` is still alive.
https://github.com/monacoinproject/monacoin/blob/master-0.17/src/chainparams.cpp#L254

If you are in a hurry, please addnode the IP address of the image.
I add a seeder for testnet.

P.S. You need to use IPv6, so you can use this address(my node).
monacoin-cli addnode [2001:e42:102:1505:160:16:59:119]:19403 add

**Comment by wakiyamap** [comment]
I added seeder.
I believe the next version will make it easier to connect.
